### PR TITLE
Cherrypicks for release 0.40.0 final

### PR DESCRIPTION
**Pull request by sklam**
Include PR:
- https://github.com/numba/llvmlite/pull/935
- https://github.com/numba/llvmlite/pull/939
- https://github.com/numba/llvmlite/pull/940

### CODE REVIEW

**Comment by sklam** [comment]
> BFID: `llvmlite_200`

All green

**Comment by sklam** [comment]
Will need https://github.com/numba/llvmlite/pull/939

**Comment by stuartarchibald** [comment]
As of 63a445f, local manual verification via cherry-pick of merge commits from #935 and #939 onto a copy of `release0.40` suggests that the diff in this patch is correct, visual inspection suggests the same.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch, the contents of this change is approved pending CI build confirmation.

**Comment by sklam** [comment]
> BFID: `llvmlite_203`

build is okay. just some network problems on linux-aarch64

**Review by stuartarchibald — APPROVED** [review]
This is re-approved following the addition of c47dd2d to accommodate #940. Manual replay of the cherry-pick checks out against this branch, it also looks as expected on inspection. Thanks for the update @sklam.

**Pull request merged**
