### PR TITLE
Fix issue #880 by ensuring all sources are compiled under FreeBSD.

### PR DESCRIPTION
**Pull request by ke6jjj**

### CODE REVIEW

**Comment by esc** [comment]
Fixes #880

**Comment by esc** [comment]
doc build failure unrelated to PR, fix is here: https://github.com/numba/llvmlite/pull/998

**Comment by esc** [comment]
@ke6jjj can you rebase on `main` that has the RTD fix.

**Comment by gmarkall** [comment]
This will also conflict with #1002 - do we want to roll this into it?

**Comment by esc** [comment]
> This will also conflict with #1002 - do we want to roll this into it?

Yes, please do, I did want to include this fix in the upcoming 0.41.1 release -- so including it there seems fine.

**Comment by esc** [comment]
@ke6jjj thank you again for the submission. @gmarkall did some work on fixing things today. We decided that this does not need to be cherry-picked into a different PR or rebased either. We will assume that this PR will not break the doc build so we will merge it anyway, despite the failing RTD test.

**Pull request merged**
