### PR TITLE
slight rearrangement of intro

### PR DESCRIPTION
**Pull request by abebeos**
* Start with llvmlite, not llvmpy
* Move llvmpy comparison to section "Why llvmlite"
* Slight reformatting

### CODE REVIEW

**Comment by esc** [comment]
@abebeos thanks for this, it looks good. While you are there, would you mind taking a look at the docs here: 

https://llvmlite.readthedocs.io/en/latest/#llvmlite

I think it would be good if the README and the landing page of the documentation are consistent, uniform and coherent. I would probably recommend trying to use a similar text across both documentation sites, but perhaps make the README one shorter and let them point to the sphinx based documentation for more details. What do you think?

**Comment by abebeos** [comment]
@esc,, me starting my cleanup, can this go in? Alternatively, please feel super-free to close unmerged.

**Comment by esc** [comment]
@abebeos thanks for the ping, I think I will leave it open in case someone would like to pick this up.

**Comment by abebeos** [comment]
> I think I will leave it open

Oh! I'm nearly unable to "abandon" my PRs. I need them either closed-merged, or closed-unmerged - thus they disappear from my internal radar, and from githubs radar (https://github.com/pulls) - otherwise not getting closure.

The tiny change is anyways "self-sufficient", so it can go in anyways (doc can be later revised fully).

(Note that I'm here in the role of a simple contributor, who was irritated by something in the docs, took the effort to suggest a fix via a PR, and then continued his main task)

**Comment by esc** [comment]
@abebeos as you wish, I have marked it for merge during the next merge window.

**Comment by abebeos** [comment]
@esc, you make contributing here a nice experience!

**Comment by esc** [comment]
@abebeos thank you for the kind words!

**Pull request merged**
