### PR TITLE
Enable Intel SVML-enabled auto-vectorization for all the transcendentals

### PR DESCRIPTION
**Pull request by anton-malakhov**
This patch allows to enable SVML in LLVM correctly on all the platforms and provides a way to choose faster functions by loosing some accuracy via fastmath=True argument in Numba

Credit to @dvnagorny for the LLVM patch

### CODE REVIEW

**Comment by anton-malakhov** [comment]
@seibert Any update on this? Unlike changes in Numba, the changes here are opt-in and will not hurt anything else.

**Comment by seibert** [comment]
We're sorting out one remaining Numba test failure related to the LLVM 6 transition so we can merge those two PRs first.

**Comment by stuartarchibald** [comment]
I've built llvmdev, then llvmlite and finally Numba against this patch and the current test suites for the Numba/llvmlite pass.

**Comment by seibert** [comment]
In that case, I vote we merge this PR while we keep working on the LLVM 6 issues.

**Comment by stuartarchibald** [comment]
Agreed. Thanks for the patch. Merging.

**Pull request merged**
