### PR TITLE
Improvements to llvmdev build scripts

### PR DESCRIPTION
**Pull request by ARF1**
Improvements:
- allow setting the targets to be built with the environment variable `LLVM_TARGETS_TO_BUILD`
- allow building on all compatible Visual Studio versions
- quote path strings to fix issues with paths with spaces

### CODE REVIEW

**Comment by esc** [comment]
@ARF1 awesome, thank you! @sklam can you take a look at this one.

**Comment by stuartarchibald** [comment]
Thanks for the patch. Parts of this I think may be something to consider rolling into the LLVM 9 upgrade. Any non-windows specific changes would also need making symmetrically on the unix side.

**Comment by ARF1** [comment]
@stuartarchibald All non-windows specific changes have been made symmetrically on the unix side.

That said, I think it would be nice if the logical and visual structure of the windows and the unix scripts were more similar. That would make maintenance easier since it would be easier to find equivalent sections / variables in the two scripts. What do you think? Should I align the windows script with the unix script?

**Comment by esc** [comment]
@ARF1 thanks for submitting this. With the last released version of llvmlite, we upgraded to LLVM 10, and so now this PR has conflicts with master. I'd like to include the changes however for the next llvmlite release (including LLVM 11) about 10 weeks from now. Is there any chance you could rebase this, fixup the conflicts and make the changes with the alignment of the scripts?

**Comment by esc** [comment]
This PR is needed now as our build farm is migrating to Windows 10.

**Comment by esc** [comment]
@ARF1 thank you again for submitting this. I have cherry picked 🍒 the two commits into the PR at #670 and built on top of them. This means the changes/commits were accepted but will be merged as part of a different PR, so I will close this one now. Thank you again for your efforts on this front it helped a lot to get Windows 10 support implemented.

**Pull request closed without merging**
