### PR TITLE
Allow adding comments to generated IR

### LINKED ISSUE #962: Allow inserting comments using IRBuilder
I'm proposing adding a comment pseudo-instruction to `IRBuilder` that inserts comments into the generated IR. I most use cases, the IR is immediately parsed by LLVM and the comments will be lost, but this could be useful for debugging and generating tutorial information.

### PR DESCRIPTION
**Pull request by apmasell**
As titled.

Closes #962

### CODE REVIEW

**Comment by esc** [comment]
> What documentation would need updating?

The documentation for llvmlite isn't generated automatically, so I think this will need an entry for the `comment` function in:

https://llvmlite.readthedocs.io/en/latest/user-guide/ir/ir-builder.html#miscellaneous

**Comment by esc** [comment]
I have made an issue to track that the llvmlite docs should be moved to use `autodoc`: https://github.com/numba/llvmlite/issues/972

**Comment by esc** [comment]
@apmasell this looks good. One last request: can you synchronise the docstring in the code-base and the text in the RST based documentation? I.e. such that they have the same verbatim text. That would save some time when we move to `autodoc` in future, because we will nuke all the "manually created" docs.

**Comment by esc** [comment]
> Okay. Synchronized.

Great, waiting for CI and will then merge!

**Comment by esc** [comment]
@apmasell looks like flake8 is reporting some tabs and space mixing:

```
llvmlite/ir/builder.py:1050:1: W191 indentation contains tabs
llvmlite/ir/builder.py:1050:1: E101 indentation contains mixed spaces and tabs
llvmlite/ir/builder.py:1051:1: W191 indentation contains tabs
llvmlite/ir/builder.py:1051:1: E101 indentation contains mixed spaces and tabs
llvmlite/ir/builder.py:1052:1: W191 indentation contains tabs
llvmlite/ir/builder.py:1052:1: E101 indentation contains mixed spaces and tabs
```

**Comment by apmasell** [comment]
Fixed.

**Pull request merged**
