### PR TITLE
removed misleading sentence

### PR DESCRIPTION
**Pull request by abebeos**
Section is about "compiling LLVM", so going straight to the point.

### CODE REVIEW

**Comment by esc** [comment]
@abebeos thank you for submitting this. I rendered the documentation just now and it looks like:

Screen Shot 2021-01-07 at 12 12 13

It seems the command `conda install -c numba llvmdev` is now out of context? Or did I miss something?

**Comment by abebeos** [comment]
[...]
> It seems the command `conda install -c numba llvmdev` is now out of context? Or did I miss something?

yes. actually now redundant, so removed.

**Comment by esc** [comment]
@abebeos thank you for fixing this up. @stuartarchibald @seibert @sklam what are your thoughts on this. Do you think we should perhaps move the hint elsewhere instead of deleting it outright?

**Comment by abebeos** [comment]
I've now understood that I had... misunderstood.

Closing, as it is in essence correct (should just be rewritten at some point, at this moment I've no suggestions on how to achieve better clarity).

**Comment by esc** [comment]
@abebeos thank you for following up. I agree that the overall structure isn't entirely favorable but I also don't quite know yet how to improve it.

**Pull request closed without merging**
