### PR TITLE
docs edits from InfoPros

### PR DESCRIPTION
**Pull request by electronwill**
docs edits from InfoPros

### CODE REVIEW

**Comment by electronwill** [comment]
@sklam , the edits from the InfoPros documentation contractors are ready to merge and deploy once you approve.

We did notice four things you may want to look at:

- https://llvmlite.readthedocs.io/en/latest/binding/passmanager.html add_type_based_alias_analysis_pass has no link.
- https://llvmlite.readthedocs.io/en/latest/ir/types.html IdentifiedStructType needs documentation.
- https://llvmlite.readthedocs.io/en/latest/ir/types.html#llvmlite.ir.IntType currently shows "class llvmlite.ir.IntType(bits)" with the attribute "width"; should the attribute be "bits" instead?
- https://llvmlite.readthedocs.io/en/latest/ir/builder.html has a broken link "Itanium exception handling ABI" to https://mentorembedded.github.io/cxx-abi/abi-eh.html . Possibly this should now be https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html ?

**Comment by kerrywatson1** [comment]
Hi Siu @sklam,  

As we discussed, only 2 items remain for you to edit:

1. Item IdentifiedStructType is commented out in original docs, not actually documented anywhere.
Resolution: **Siu will edit.**

2. Is printed.unctions correct? Not printed.functions?
Resolution: it's a typo! Changed to printed.functions.

3. The above sentence says the following are methods, but in the code, each is marked up as a function. I.e., using the function:: directive instead of the method:: directive. I didn't want to change them in case there was a reason for this.]
Resolution: change to function:: directive.

4. http://llvm.org/docs/Passes.html#scalarrepl-scalar-replacement-of-aggregates —> # has been removed from page AND In the above sentence, does "it" refer to: the documentation, the transformation, or the function?
Resolution: "it" means "the pass"

5. add_type_based_alias_analysis_pass —> link missing.
Resolution: **Siu will add some text.**

**Comment by electronwill** [comment]
@sklam if you like, we can make redirects from the deleted pages to the new pages with the same content. However, to do that one of us will need access to the readthedocs.org project at https://readthedocs.org/projects/llvmlite/ . Would you like us to make the redirects?

**Comment by electronwill** [comment]
Oh, and my readthedocs.org username is wwarner .

**Comment by sklam** [comment]
@electronwill , Yes, redirects would be nice.  I have added you to rtd.

**Comment by electronwill** [comment]
Thanks!

All redirects have now been added and tested:

https://llvmlite.readthedocs.io/en/latest/install/index.html
https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html

https://llvmlite.readthedocs.io/en/latest/binding/analysis.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/analysis-utilities.html

https://llvmlite.readthedocs.io/en/latest/binding/dylib.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/dynamic-libraries.html

https://llvmlite.readthedocs.io/en/latest/binding/engine.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/execution-engine.html

https://llvmlite.readthedocs.io/en/latest/binding/examples.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/examples.html

https://llvmlite.readthedocs.io/en/latest/binding/index.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/index.html

https://llvmlite.readthedocs.io/en/latest/binding/initfini.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/initialization-finalization.html

https://llvmlite.readthedocs.io/en/latest/binding/modules.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/modules.html

https://llvmlite.readthedocs.io/en/latest/binding/passmanager.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/optimization-passes.html

https://llvmlite.readthedocs.io/en/latest/binding/targets.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/target-information.html

https://llvmlite.readthedocs.io/en/latest/binding/values.html
https://llvmlite.readthedocs.io/en/latest/user-guide/binding/value-references.html

https://llvmlite.readthedocs.io/en/latest/developer/index.html
https://llvmlite.readthedocs.io/en/latest/contributing.html

https://llvmlite.readthedocs.io/en/latest/intro/index.html
https://llvmlite.readthedocs.io/en/latest/index.html

https://llvmlite.readthedocs.io/en/latest/ir/builder.html
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/ir-builder.html

https://llvmlite.readthedocs.io/en/latest/ir/examples.html
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/examples.html

https://llvmlite.readthedocs.io/en/latest/ir/index.html
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/index.html

https://llvmlite.readthedocs.io/en/latest/ir/modules.html
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/modules.html

https://llvmlite.readthedocs.io/en/latest/ir/types.html
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/types.html

https://llvmlite.readthedocs.io/en/latest/ir/values.html
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/values.html

**Pull request merged**
