### PR TITLE
Add optional named arguments to functions

### PR DESCRIPTION
**Pull request by prafael18**

### CODE REVIEW

**Comment by esc** [comment]
@prafael18 thanks for submitting this, I have added it to the review queue.

**Comment by esc** [comment]
@prafael18 would it be feasible to add tests for this?

**Review by gmarkall — CHANGES_REQUESTED** [review]
In addition to tests, the documentation will also need updating to reflect the additional arg name support.

**Comment by gmarkall** [comment]
Having a bit of a tidy-up - it seems this PR is unlikely to proceed further.

**Pull request closed without merging**
