### PR TITLE
Introduce Cygwin support

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
Make building and running on Cygwin. Tested on x86_64 only.

### CODE REVIEW

**Comment by Sonic-Amiga** [comment]
Hello dear maintainers! I am working on a project, using numba, on Cygwin. I found out that numba does not currently work on this platform and would like to offer a fix.

**Comment by Sonic-Amiga** [comment]
Fixed format

**Comment by gmarkall** [comment]
Thanks very much for the PR, I've queued it for review.

**Comment by Sonic-Amiga** [comment]
Hello! Almost a year has passed. Today i needed to reinstall the library from pip after python version upgrade and stumbled upon this problem again. Why aren't you reviewing the patch ?

**Comment by esc** [comment]
@Sonic-Amiga we are sorry that we were not yet able to look at your patch. There have been insufficient hands during the last year and we simply have not gotten around to it yet. Your submission is appreciated none-the-less and we hope review and include this eventually.

**Comment by esc** [comment]
The plan for this is to have someone check if this works on cygwin and if it works once, to merge and keep. We will not setup CI for cygwin to keep ensuring this works.

**Comment by gmarkall** [comment]
@Sonic-Amiga I tried to test this today but I'm having some difficulty building LLVM on Cygwin - can you suggest the correct set of steps for obtaining or building LLVM on Cygwin please?

**Comment by Sonic-Amiga** [comment]
Hello! I didn't build LLVM, i have it preinstalled. Using a Cygwin installer you can get llvm, llvm-devel, etc packages, just like on any Linux machine.

**Comment by Sonic-Amiga** [comment]
...so i just build and install llvmlite in a regular way, "python3 setup.py --install", IIRC. Any prerequisites are obtained with pip, as usual.

**Comment by gmarkall** [comment]
@Sonic-Amiga Thanks for the info - what LLVM version do you have from the Cygwin installer?

**Comment by Sonic-Amiga** [comment]
Hello! I've checked what's currently installed on my home PC (this is what i submitted the patch with), it's 8.0.1. Seems to be still up to date.

**Review by gmarkall — CHANGES_REQUESTED** [review]
Building the commit 53edf26 from https://github.com/Sonic-Amiga/llvmlite (the commit from this PR) does work OK with LLVM 8.0.1 from the Cygwin installer. I built with:

```
python setup.py develop
```

And got the results from a test run:

```
$ python runtests.py
..s.s........................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 253 tests in 2.215s

OK (skipped=2)
```

However, merging this into current master doesn't result in a working build. First, the LLVM version check fails:

```
$ python setup.py develop
/cygdrive/c/work/numbadev/venvs/cygwin-llvmlite/lib/python3.8/site-packages/setuptools/dist.py:463: UserWarning: Normalizing '0.37.0dev0+25.g7377b47' to '0.37.0.dev0+25.g7377b47'
  warnings.warn(tmpl.format(**locals()))
running develop
running egg_info
creating llvmlite.egg-info
writing llvmlite.egg-info/PKG-INFO
writing dependency_links to llvmlite.egg-info/dependency_links.txt
writing top-level names to llvmlite.egg-info/top_level.txt
writing manifest file 'llvmlite.egg-info/SOURCES.txt'
reading manifest file 'llvmlite.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching 'CMakeCache.txt' found anywhere in distribution
writing manifest file 'llvmlite.egg-info/SOURCES.txt'
running build_ext
/cygdrive/c/work/numbadev/venvs/cygwin-llvmlite/bin/python /cygdrive/c/work/numbadev/llvmlite/ffi/build.py
LLVM version... 8.0.1

Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/ffi/build.py", line 222, in <module>
    main()
  File "/cygdrive/c/work/numbadev/llvmlite/ffi/build.py", line 216, in main
    main_posix('cygwin', '.dll')
  File "/cygdrive/c/work/numbadev/llvmlite/ffi/build.py", line 172, in main_posix
    raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '8.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

error: command '/cygdrive/c/work/numbadev/venvs/cygwin-llvmlite/bin/python' failed with exit status 1
```

Ignoring the LLVM version check results in a compile error:

```
$ LLVMLITE_SKIP_LLVM_VERSION_CHECK=1 python setup.py develop
/cygdrive/c/work/numbadev/venvs/cygwin-llvmlite/lib/python3.8/site-packages/setuptools/dist.py:463: UserWarning: Normalizing '0.37.0dev0+25.g7377b47' to '0.37.0.dev0+25.g7377b47'
  warnings.warn(tmpl.format(**locals()))
running develop
running egg_info
writing llvmlite.egg-info/PKG-INFO
writing dependency_links to llvmlite.egg-info/dependency_links.txt
writing top-level names to llvmlite.egg-info/top_level.txt
reading manifest file 'llvmlite.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching 'CMakeCache.txt' found anywhere in distribution
writing manifest file 'llvmlite.egg-info/SOURCES.txt'
running build_ext
/cygdrive/c/work/numbadev/venvs/cygwin-llvmlite/bin/python /cygdrive/c/work/numbadev/llvmlite/ffi/build.py
LLVM version... 8.0.1

================================================================================
WARNING * WARNING * WARNING * WARNING * WARNING * WARNING * WARNING * WARNING
================================================================================
The LLVM version check for supported versions has been overridden.
This is unsupported behaviour, llvmlite may not work as intended.
Requested LLVM version: 8.0.1
================================================================================
WARNING * WARNING * WARNING * WARNING * WARNING * WARNING * WARNING * WARNING
================================================================================

SVML not detected
# static-libstdc++ avoids runtime dependencies on a
# particular libstdc++ version.
g++  -shared   -I/usr/include -std=gnu++11 -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp -o libllvmlite.dll  -L/usr/lib -flto -Wl,--exclude-libs=ALL -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMMIRParser -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMCoverage -lLLVMMCA -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMXRay -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMWebAssemblyDisassembler -lLLVMWebAssemblyCodeGen -lLLVMWebAssemblyDesc -lLLVMWebAssemblyAsmPrinter -lLLVMWebAssemblyAsmParser -lLLVMWebAssemblyInfo -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430Disassembler -lLLVMMSP430CodeGen -lLLVMMSP430AsmParser -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMOptRemarks -lLLVMWindowsManifest -lLLVMTextAPI -lLLVMFuzzMutate -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMBitWriter -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle
passmanagers.cpp: In function ‘void LLVMPY_ReportAndResetTimings(const char**)’:
passmanagers.cpp:35:30: error: too many arguments to function ‘void llvm::reportAndResetTimings()’
   35 |     reportAndResetTimings(&os);
      |                              ^
In file included from passmanagers.cpp:16:
/usr/include/llvm/IR/PassTimingInfo.h:33:6: note: declared here
   33 | void reportAndResetTimings();
      |      ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile.cygwin:22: libllvmlite.dll] Error 1
Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/ffi/build.py", line 222, in <module>
    main()
  File "/cygdrive/c/work/numbadev/llvmlite/ffi/build.py", line 216, in main
    main_posix('cygwin', '.dll')
  File "/cygdrive/c/work/numbadev/llvmlite/ffi/build.py", line 202, in main_posix
    subprocess.check_call(['make', '-f', makefile])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.cygwin']' returned non-zero exit status 2.
error: command '/cygdrive/c/work/numbadev/venvs/cygwin-llvmlite/bin/python' failed with exit status 1
```

Working around this with:

```diff
diff --git a/ffi/passmanagers.cpp b/ffi/passmanagers.cpp
index 0206d17..d2fdcf8 100644
--- a/ffi/passmanagers.cpp
+++ b/ffi/passmanagers.cpp
@@ -32,7 +32,7 @@ API_EXPORT(void)
 LLVMPY_ReportAndResetTimings(const char **outmsg) {
     std::string osbuf;
     raw_string_ostream os(osbuf);
-    reportAndResetTimings(&os);
+    //reportAndResetTimings(&os);
     os.flush();
     *outmsg = LLVMPY_CreateString(os.str().c_str());
 }
```

enables the compilation to complete, but the binding doesn't work:

```
$ python runtests.py
EEEE.....
======================================================================
ERROR: llvmlite.tests.test_binding (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: llvmlite.tests.test_binding
Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 95, in __getattr__
    return self._fntab[name]
KeyError: 'LLVMPY_AddRefPrunePass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/tests/test_binding.py", line 16, in <module>
    from llvmlite import binding as llvm
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/__init__.py", line 10, in <module>
    from .passmanagers import *
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/passmanagers.py", line 282, in <module>
    ffi.lib.LLVMPY_AddRefPrunePass.argtypes = [ffi.LLVMPassManagerRef, c_int,
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 98, in __getattr__
    cfn = getattr(self._lib, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'LLVMPY_AddRefPrunePass' not found


======================================================================
ERROR: llvmlite.tests.test_ir (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: llvmlite.tests.test_ir
Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 95, in __getattr__
    return self._fntab[name]
KeyError: 'LLVMPY_AddRefPrunePass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/tests/test_ir.py", line 14, in <module>
    from llvmlite import binding as llvm
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/__init__.py", line 10, in <module>
    from .passmanagers import *
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/passmanagers.py", line 282, in <module>
    ffi.lib.LLVMPY_AddRefPrunePass.argtypes = [ffi.LLVMPassManagerRef, c_int,
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 98, in __getattr__
    cfn = getattr(self._lib, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'LLVMPY_AddRefPrunePass' not found


======================================================================
ERROR: test_imports (llvmlite.tests.test_llvmpy.TestMisc)
Sanity-check llvmpy APIs import correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 95, in __getattr__
    return self._fntab[name]
KeyError: 'LLVMPY_AddRefPrunePass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/tests/test_llvmpy.py", line 15, in test_imports
    from llvmlite.llvmpy.core import Constant, Type, Builder  # noqa F401
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/llvmpy/core.py", line 4, in <module>
    from llvmlite import binding as llvm
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/__init__.py", line 10, in <module>
    from .passmanagers import *
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/passmanagers.py", line 282, in <module>
    ffi.lib.LLVMPY_AddRefPrunePass.argtypes = [ffi.LLVMPassManagerRef, c_int,
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 98, in __getattr__
    cfn = getattr(self._lib, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'LLVMPY_AddRefPrunePass' not found

======================================================================
ERROR: llvmlite.tests.test_refprune (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: llvmlite.tests.test_refprune
Traceback (most recent call last):
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 95, in __getattr__
    return self._fntab[name]
KeyError: 'LLVMPY_AddRefPrunePass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/tests/test_refprune.py", line 3, in <module>
    from llvmlite import binding as llvm
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/__init__.py", line 10, in <module>
    from .passmanagers import *
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/passmanagers.py", line 282, in <module>
    ffi.lib.LLVMPY_AddRefPrunePass.argtypes = [ffi.LLVMPassManagerRef, c_int,
  File "/cygdrive/c/work/numbadev/llvmlite/llvmlite/binding/ffi.py", line 98, in __getattr__
    cfn = getattr(self._lib, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'LLVMPY_AddRefPrunePass' not found


----------------------------------------------------------------------
Ran 9 tests in 0.028s

FAILED (errors=4)
```

@Sonic-Amiga Have you tried your patch on top of a recent revision (e.g. `master`) of llvmlite? If so, did you take any additional steps to make it work? Am I missing something here?

**Comment by Sonic-Amiga** [comment]
Hi!
No, i haven't tried rebasing. From logs i see that in the meanwhile minimum LLVM version bumped up to 9.
Unfortunately it looks like Cygwin doesn't currently have llvm v9. 8.0.1 is the current one.

I don't know what to say. I guess dropping llvm 8 in your project is kinda political decision, not to be disputed. I don't have time to port llvm 9 myself, so my hands go down here. :(

**Comment by esc** [comment]
@gmarkall @Sonic-Amiga thank you both for diligently looking into this! It seems like this issue is now stalled, awaiting the arrival of newer LLVMs for Cygwin.  We don't have a label for this at the moment, so this textual description will have to suffice. As for LLVM, they tend to be backwards incompatible, so llvmlite follows the policy to only support a single LLVM per platform at any given time.

**Comment by esc** [comment]
> Ok, i've got the idea. Your library specifies explicit llvmlite version range, so older code would just request older llvmlite and it will be okay, given pip error somehow doesn't manifest itself. It's not very interesting for us here anyways...

Correct. The LLVM versions supported by each llvmlite release can be viewed here: https://github.com/numba/llvmlite#compatibility

**Comment by Sonic-Amiga** [comment]
Ops, my head got screwed up. :) Too much time has passed, i don't remember things.

I have two patches: for numba itself and for llvmlite. So this PR is for llvmlite. I don't remember why i didn't post numba patch itself. Probably because llvmlite is a prerequisite and we need to get it compiling first.

I am work now and my versions here are:

llvmlite      0.32.1+0.gaa11b12.dirty
numba      0.50.0.dev0+191.g0c976cd0a.dirty

So is it hard to bring back llvm 8 support for llvmlite ? Or is it strictly a political decision to move forward ?

If you don't mind i'll open a corresponding PR against numba repository too so that it at least doesn't get lost in time.

**Comment by Sonic-Amiga** [comment]
I've finally remembered everything.
numba itself is incomplete.It builds and installs, but the JIT doesn't work. There's some problem with symbol resolving; i wasn't able to figure out why. So i decided not to try posting a nonfunctional patch.

**Comment by esc** [comment]
> Ops, my head got screwed up. :) Too much time has passed, i don't remember things.
> 
> I have two patches: for numba itself and for llvmlite. So this PR is for llvmlite. I don't remember why i didn't post numba patch itself. Probably because llvmlite is a prerequisite and we need to get it compiling first.
> 
> I am work now and my versions here are:
> 
> llvmlite 0.32.1+0.gaa11b12.dirty
> numba 0.50.0.dev0+191.g0c976cd0a.dirty
> 
> So is it hard to bring back llvm 8 support for llvmlite ? Or is it strictly a political decision to move forward ?

It is both a political and a technical decision. LLVMs are not exactly backwards compatible and we don't have the resources (testing, bug triaging etc..) to support more than two LLVMs if the platforms demand it. (E.g. `aarch64` is stuck on LLVM 9.0 due to a bug.) I am not sure how hard it would be technically, but I can imagine it may be rather involved, especially if we want testing automation to go with  it. Also, we plan to update to LLVM 11 for the next (0.37)  release of llvmlite.  I think, currently it is very, very unlikely that we will bring back official LLVM 8 support for llvmlite. On top of all of this, Numba/llvmlite do need a custom compiled LLVM version to function correctly, you can read more about it here: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#what-to-be-aware-of-when-using-a-system-provided-llvm-package

> If you don't mind i'll open a corresponding PR against numba repository too so that it at least doesn't get lost in time.

We don't mind, however the patch -- like this one -- will most likely be  stalled awaiting LLVM 11 support for Cygwin.

Hope this helps!

**Comment by Sonic-Amiga** [comment]
@gmarkall Hello! Long time...
Sorry, at the moment my project, for which i did it, made progress in a different environment. Frankly speaking, personally i don't have enough time and/or expertise to bring up LLVM 11 on Cygwin.
So, i don't know what happens to this task. Probably nothing. :( Also i see Cygwin losing popularity due to Linux subsystem having been introduced.

**Comment by gmarkall** [comment]
Indeed, a long time... Apologies!

> Sorry, at the moment my project, for which i did it, made progress in a different environment.

I'm glad to hear you made progress with your project - out of interest, is it still using llvmlite? If so, is it public?

> Frankly speaking, personally i don't have enough time and/or expertise to bring up LLVM 11 on Cygwin.

I understand - I think I would have similar barriers to doing that.

> So, i don't know what happens to this task. Probably nothing. :( 

OK - whilst I'm grateful for all your efforts so far (and I hope you won't be deterred from potential contributions in the future), I wonder if we should close this PR if we're not going to be able to proceed further with it?

> Also i see Cygwin losing popularity due to Linux subsystem having been introduced.

I think you make a good point about Cygwin vs. WSL (and I note that llvmlite / Numba and CUDA too all work on WSL2 unmodified).

**Comment by Sonic-Amiga** [comment]
>  is it still using llvmlite? If so, is it public?

 Hello! No, it's not public; in fact it's using llvmlite via numba, which is used to speed up some internal simulation, written in python. It's not even a part of the product and not a part of the release.
 Since this all happens at work, i am under NDA, i am not allowed to tell what the thing actually does.

> OK - whilst I'm grateful for all your efforts so far (and I hope you won't be deterred from potential contributions in the future), I wonder if we should close this PR if we're not going to be able to proceed further with it?

 Well, it's your adminstrative stuff, you can close.
 Merry (past) Christmas and happy New Year!

**Comment by gmarkall** [comment]
> Hello! No, it's not public; in fact it's using llvmlite via numba, which is used to speed up some internal simulation, written in python. It's not even a part of the product and not a part of the release. Since this all happens at work, i am under NDA, i am not allowed to tell what the thing actually does.

Thanks for sharing a little of the details - glad you're still able to make use of Numba and llvmlite :-)

> Well, it's your adminstrative stuff, you can close. Merry (past) Christmas and happy New Year!

OK, will do - many thanks for confirming that it's OK - Merry Christmas and a happy New Year to you too! (Do have a good evening tonight :slightly_smiling_face:)

**Pull request closed without merging**
