### PR TITLE
Add initializer for asm parser

### PR DESCRIPTION
**Pull request by sklam**
needed at https://github.com/numba/numba/pull/2149/files#diff-0faf9dcbe850c373d6769c3b1519a29aR194

### CODE REVIEW

**Comment by pitrou** [comment]
The test failed on Travis-CI.

**Comment by sklam** [comment]
ah, the asm format is different.   I should just test for the `nop`.

**Comment by pitrou** [comment]
Should we add a doc for this? See http://llvmlite.pydata.org/en/latest/binding/initfini.html

**Comment by sklam** [comment]
Yes, I will add doc

**Pull request merged**
