### PR TITLE
bump max Python version to 3.11

### PR DESCRIPTION
**Pull request by esc**
As title

### CODE REVIEW

**Comment by leftys** [comment]
It would be really helpful to merge this one. This bug breaks llvm with python3.11, which also blocks numba and therefore a lot of python data science tools. By the way, final version of python 3.11 is expected to be released in about a month if things go according to schedule.

**Comment by esc** [comment]
> It would be really helpful to merge this one. This bug breaks llvm with python3.11, which also blocks numba and therefore a lot of python data science tools. By the way, final version of python 3.11 is expected to be released in about a month if things go according to schedule.

Thank you for asking about this, I will answer briefly to do some expectation management. We have been monitoring the Python 3.11 situation since last year and llvmlite is likely to be fine, only the version number needs to be bumped as in this PR.

However, Numba is s different matter. Numba interfaces with the Python bytecode which has changed significantly again with 3.11. We do have some stuff in place already, but we can't make any guarantees about Numba being 3.11 compatible on the day of its release. For previous Python version 3.9 and 3.10 took 6 and 3 months respectively. 

You can follow the Python 3.11 vs. Numba front here: https://github.com/numba/numba/issues/8304

Thank you again for bringing this up, we are aware that Numba is a very popular library by now and we do understand our responsibility to keep a lot of data science tools working. I can assure you, we have been working very hard over the last few months and porting Numba to 3.11 presents a significant technical challenge.

**Comment by cloud11665** [comment]
Are there any reasons for not merging this one just for llvmlite ?
All tests pass on 3.11.0rc2 (which is the default /bin/python on fedora 37).

**Comment by esc** [comment]
> Are there any reasons for not merging this one just for llvmlite ? All tests pass on 3.11.0rc2 (which is the default /bin/python on fedora 37).

Our build and release process is based around `conda`. We can't run CI reliably without an official Python 3.11 package being released via anaconda.org. Hence we are currently blocked by that. We hope to get this merged up and a new version released as soon as the required packages become available. Until then, please be patient, thank you!

**Comment by cloud11665** [comment]
Oh ok, I see. No worries then.

**Comment by esc** [comment]
FWIW: this had a conflict against `main` - I have rebased this now and fixed the conflict.

**Comment by maxnoe** [comment]
> Hence we are currently blocked by that. We hope to get this merged up and a new version released as soon as the required packages become available. 

conda-forge had python 3.11 packages the day after the release

**Comment by esc** [comment]
> > Hence we are currently blocked by that. We hope to get this merged up and a new version released as soon as the required packages become available.
> 
> conda-forge had python 3.11 packages the day after the release

@maxnoe yes, thank you for mentioning that. We are aware of the conda-forge efforts. We recently had a developer meeting about this with everyone who is a stakeholder in the build and release process. We came to the conclusion that conda-forge packages would be to unstable for our needs. We have experimented with using conda-forge for build and release before but hit too many roadblocks. IIRC this was mostly related to broken compiler packages, broken interpreter packages and lack of reliable, bare-metal support for the more esoteric architectures that Numba targets. So, for the time being we will stick to this decision. I would be open to revisiting this issue however, in due time, as and when we get the impression that conda-forge has become suitable for our needs.

**Comment by stuartarchibald** [comment]
Under Python 3.11 this `DeprecationWarning` is issued which is causing Numba's `numba.tests.test_import.TestNumbaImport.test_no_accidental_warnings` test to fail:
```
    from llvmlite.binding import ffi
  File "<path>/site-packages/llvmlite/binding/ffi.py", line 159, in <module>
    _lib_handle = importlib.resources.path(pkgname, _lib_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<env>/importlib/resources/_legacy.py", line 18, in wrapper
    warnings.warn(
DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
```

**Comment by maxnoe** [comment]
> We have experimented with using conda-forge for build and release before but hit too many roadblocks.

I would kindly encourage you to re-evaluate this decision (or in general the dependency on anaconda python builds for your release process). Python 3.11 is released for a relatively long time now and for whatever reason, there are still no anaconda packages, not even official feedback in the corresponding anaconda-issues issue when it might come:
https://github.com/ContinuumIO/anaconda-issues/issues/13082 

This dependency also seems to make it impossible to CI test on release candidates and have changes ready once a release of python is made.

**Comment by maxnoe** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/13082#issuecomment-1386341685

**Comment by esc** [comment]
> > We have experimented with using conda-forge for build and release before but hit too many roadblocks.
> 
> I would kindly encourage you to re-evaluate this decision (or in general the dependency on anaconda python builds for your release process). 

Thank you for your feedback, rest assured that we are also fairly frustrated with this.  However, I'd like to manage some expectations here:  due to capacity constraints and other more high priority threads we are unlikely to have the bandwidth to re-evaluate this decision for the time being. I can only appeal to your continued patience here, thank you.

**Comment by esc** [comment]
With [7eeedcb](https://github.com/numba/llvmlite/pull/869/commits/7eeedcbc54d687c3e47227950aeae40e80b83828) I have also added the 3.11 trove classfier.

**Review by sklam — APPROVED** [review]
LGTM. This has been used for testing numba's `py3.11` branch and has been passing

**Pull request merged**
