### PR TITLE
Permit building against LLVM 7.1.0

### LINKED ISSUE #480: llvmlite rejects llvm 7.1.0
LLVM 7.1.0 has been released, and should be entirely API compatible with LLVM 7.0.x. However, llvmlite rejects it outright:

```
python2.7 setup.py build        
running build                           
got version from expanded keyword {'version': '0.28.0', 'full': '685b7b6941617f616f3f0b609e381af52da26782'}
running build_ext                                                                                                                                 
/usr/bin/python2.7 /tmp/portage/dev-python/llvmlite-0.28.0/work/llvmlite-0.28.0/ffi/build.py                                                      
LLVM version... 7.1.0                                                                                                                             
                                                                                                                                                  
Traceback (most recent call last):                                                                                                                
  File "/tmp/portage/dev-python/llvmlite-0.28.0/work/llvmlite-0.28.0/ffi/build.py", line 167, in <module>                                         
    main()                                                          
  File "/tmp/portage/dev-python/llvmlite-0.28.0/work/llvmlite-0.28.0/ffi/build.py", line 157, in main
    main_posix('linux', '.so')                                                                                                                    
  File "/tmp/portage/dev-python/llvmlite-0.28.0/work/llvmlite-0.28.0/ffi/build.py", line 119, in main_posix
    raise RuntimeError(msg)                                                                                                                       
RuntimeError: Building llvmlite requires LLVM 7.0.x. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

```

### PR DESCRIPTION
**Pull request by mgorny**
Restrict building to any 7.* version rather than 7.0.*, as 7.1.0 has
been released that is API-compatible with 7.0.*.

Fixes #480.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the PR. `llvmlite`, and in general the Numba stack, has not been tested against 7.1.0 and so whether it is valid to build against this is unknown. Current efforts are going into LLVM 8 support, is there a need to support 7.1.0 alongside LLVM 8?

**Comment by mgorny** [comment]
Yes, Gentoo is going to stabilize 7.1.0 shortly (we skipped 7.0.x due to issues). The changes upstream are tiny compared to 7.0.1, and I can say that llvmlite tests pass.

**Comment by zerothi** [comment]
I can add that llvmlite tests passes on my box as well for 7.1.0.

Well, except `test_version (llvmlite.tests.test_binding.TestMisc)` because it checks LLVM version 7.0.X.

**Comment by stuartarchibald** [comment]
Thanks for confirming. Due to some issues with LLVM 8 on PPC64LE `llvmlite` 0.29 is going to accept 7.0.x, 7.1.x and 8.0.x versions of LLVM. https://github.com/numba/llvmlite/pull/478 added support for doing this.

**Pull request closed without merging**
