### PR TITLE
Update for changes in LLVM 3.9

### PR DESCRIPTION
**Pull request by whitequark**
RelocMode is now Optional<RelocMode>, where None has the same meaning
as Default used to.

Data layout is no longer ever optional, so there is no need in
explicitly adding it anywhere; those APIs were removed in LLVM.

### CODE REVIEW

**Comment by pitrou** [comment]
Interesting, are these the only changes you had to make, or is it a work in progress?

**Comment by whitequark** [comment]
The only ones.

**Comment by pitrou** [comment]
I see, that's surprisingly small. Normally we would wait for 3.9.1 before making the switch, perhaps we'll try to test earlier this time.

**Comment by whitequark** [comment]
@pitrou 3.9.1 is released...

**Comment by whitequark** [comment]
Nevermind the previous comment, I misread some things.

**Comment by sklam** [comment]
I have just tested with 3.9.1.  The following test now fails:


```
======================================================================
ERROR: test_debug_info (llvmlite.tests.test_ir.TestIR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sklam/dev/llvmlite/llvmlite/tests/test_ir.py", line 315, in test_debug_info
    self.assert_valid_ir(mod)
  File "/home/sklam/dev/llvmlite/llvmlite/tests/test_ir.py", line 52, in assert_valid_ir
    llvm.parse_assembly(str(mod))
  File "/home/sklam/dev/llvmlite/llvmlite/binding/module.py", line 22, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: LLVM IR parsing error
<string>:10:123: error: invalid field 'subprograms'
!5 = distinct !DICompileUnit(file: !0, isOptimized: true, language: DW_LANG_Python, producer: "ARTIQ", runtimeVersion: 0, subprograms: !4)
                                                                                                                          ^
```

Very likely due to https://llvm.org/bugs/show_bug.cgi?id=27284

**Pull request merged**
