### PR TITLE
LLVM 15 conda recipe

### PR DESCRIPTION
**Pull request by sklam**

### CODE REVIEW

**Comment by sklam** [comment]
f0def581a930e11f730073c82b03284b370aef72 builds successfully on all platform in the buildfarm

**Comment by sklam** [comment]
passed numba testsuite when running manually on linux-64 machine

**Comment by gmarkall** [comment]
We need to merge this and build the llvmdev package, as I understand it. (This requires the setup internal to Anaconda on their build farm).

After that, I think we can switch the llvmlite CI over to use LLVM 15 by default, and start to move it from being experimental to being the default supported version.

**Comment by sklam** [comment]
BFID `llvmdev_llvm15_4`

**Comment by sklam** [comment]
> BFID `llvmdev_llvm15_4`

build passed

**Comment by sklam** [comment]
Now testing llvmdev build against llvmlite test in `llvmlite_llvm15_2`

**Comment by sklam** [comment]
`llvmlite_llvm15_3` also passed.

**Review by gmarkall — APPROVED** [review]
I had previously reviewed this and tested it locally and my understanding is that we were only waiting on a build farm run, so I think this is OK to move to RTM and build new LLVMdev 15 packages for the main channel so we can switch llvmlite over to more general testing with LLVM 15.

**Comment by gmarkall** [comment]
Marked RTM as per discussion in triage meeting.

**Pull request merged**
