### PR TITLE
Expose library name in OrcJIT tracker

### PR DESCRIPTION
**Pull request by apmasell**
Add a `name` property with the OrcJIT library name in the tracker object.

### CODE REVIEW

**Comment by esc** [comment]
@apmasell thank you for this contribution. Questions: Do you have any hints for the reviewers? Why was this change needed? Any thoughts about possible testing strategies?

**Comment by apmasell** [comment]
This change is just a convince to know the library name, which is particularly helpful when debugging. It is tested.

**Comment by esc** [comment]
> This change is just a convenience to know the library name, which is particularly helpful when debugging. It is tested.

Sounds good, thank you.

**Review by esc — APPROVED** [review]
LGTM

**Pull request merged**
