### PR TITLE
llvm::Module::GetSourceFileName

### PR DESCRIPTION
**Pull request by japendergrass**
This PR just adds a binding in `binding.ModuleRef` for llvm::Module::getSourceFileName

### CODE REVIEW

**Comment by gmarkall** [comment]
Many thanks for the PR - I'm working through the llvmlite PRs over the holiday period, so I hope to check this out over the next few days.

**Comment by japendergrass** [comment]
Done

**Review by gmarkall — CHANGES_REQUESTED** [review]
@japendergrass Many thanks for updating the PR - the code all looks good, but there's one flake8 error - I tried to push a fix to this branch but I don't have permission (maybe "Allow edits from maintainers" is unchecked, or maybe I don't have as much power over the llvmlite repo as I thought I did). If you could please fix the whitespace causing the flake8 fail, I'll approve this PR.

**Review by gmarkall — APPROVED** [review]
Many thanks for the flake8 fix, this now looks good to me!

**Comment by esc** [comment]
@japendergrass thank you for the patch! @gmarkall thank you for the review!

**Pull request merged**
