### PR TITLE
Switch to LLVM 3.7

### PR DESCRIPTION
**Pull request by pitrou**
This PR enables support for LLVM 3.7 (and, due to the usual compatibility breakage, ends support for LLVM 3.6).
One important change is that the TargetLibraryInfo APIs we were exposing are not really available anymore, at least not in a straightforward manner. The PR disables TargetLibraryInfo entirely for now, and Numba seems to run fine without that. I've yet to hear about the implications.

What is still remaining to do:
* doc fixes for the removed APIs
* doc changes for 3.6 -> 3.7
* modify and check conda recipes for llvmdev and llvmlite under Windows

Also note NVVM doesn't like the new IR.

### CODE REVIEW

**Comment by mabl** [comment]
It doesn't seem to work for me:

```
$ pip install --upgrade git+https://github.com/pitrou/llvmlite.git@llvm3.7
Collecting git+https://github.com/pitrou/llvmlite.git@llvm3.7
  Cloning https://github.com/pitrou/llvmlite.git (to llvm3.7) to /tmp/pip-oti1VK-build
Collecting enum34 (from llvmlite==0+untagged.ge76aebd)
  Using cached enum34-1.1.1.tar.gz
Installing collected packages: enum34, llvmlite
  Found existing installation: enum34 1.0.4
    DEPRECATION: Uninstalling a distutils installed project (enum34) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Not uninstalling enum34 at /usr/lib/python2.7/site-packages, outside environment /home/mabl/PhD/Software/virtualenv
  Running setup.py install for enum34
  Found existing installation: llvmlite 0.7.0
    Uninstalling llvmlite-0.7.0:
      Successfully uninstalled llvmlite-0.7.0
  Running setup.py install for llvmlite
    Complete output from command /home/mabl/PhD/Software/virtualenv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-oti1VK-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-J0LRsc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mabl/PhD/Software/virtualenv/include/site/python2.7/llvmlite:
    running install
    running build
    got version from VCS {'version': '0+untagged.ge76aebd', 'full': 'e76aebd09fe09634a99acf668a6b867510d45b34'}
    running build_ext
    /home/mabl/PhD/Software/virtualenv/bin/python2.7 /tmp/pip-oti1VK-build/ffi/build.py
    LLVM version... 3.7.0
    # static-libstdc++ avoids runtime dependencies on a
    # particular libstdc++ version.
    g++ -static-libstdc++ -shared -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wnon-virtual-dtor -Wno-comment -std=c++11 -ffunction-sections -fdata-sections -O3 -DNDEBUG -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.so -L/usr/lib -flto -Wl,--exclude-libs=ALL -lLLVMIRReader -lLLVMAsmParser -lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMProfileData -lLLVMInstCombine -lLLVMInstrumentation -lLLVMTransformUtils -lLLVMipa -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMExecutionEngine -lLLVMTarget -lLLVMAnalysis -lLLVMRuntimeDyld -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMMC -lLLVMCore -lLLVMSupport -lrt -ldl -lcurses -lpthread -lz -lm -lLLVMOProfileJIT
    /usr/bin/ld: cannot find -lLLVMOProfileJIT
    collect2: error: ld returned 1 exit status
    Makefile.linux:18: recipe for target 'libllvmlite.so' failed
    make: *** [libllvmlite.so] Error 1
    Traceback (most recent call last):
      File "/tmp/pip-oti1VK-build/ffi/build.py", line 147, in <module>
        main()
      File "/tmp/pip-oti1VK-build/ffi/build.py", line 137, in main
        main_posix('linux', '.so')
      File "/tmp/pip-oti1VK-build/ffi/build.py", line 129, in main_posix
        subprocess.check_call(['make', '-f', makefile])
      File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
    error: command '/home/mabl/PhD/Software/virtualenv/bin/python2.7' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of llvmlite
Command "/home/mabl/PhD/Software/virtualenv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-oti1VK-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-J0LRsc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mabl/PhD/Software/virtualenv/include/site/python2.7/llvmlite" failed with error code 1 in /tmp/pip-oti1VK-build
```

**Comment by mabl** [comment]
Also see this:

```llvm-config --libs 
-lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMBitWriter -lLLVMIRReader -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUUtils -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMMIRParser -lLLVMAsmParser -lLLVMLibDriver -lLLVMOption -lLLVMDebugInfoPDB -lLLVMTableGen -lLLVMOrcJIT -lLLVMLineEditor -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMDebugInfoDWARF -lLLVMPasses -lLLVMipo -lLLVMVectorize -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMInstCombine -lLLVMInstrumentation -lLLVMTransformUtils -lLLVMipa -lLLVMMC -lLLVMAnalysis -lLLVMCore -lLLVMSupport
```

All on Arch Linux

**Comment by pitrou** [comment]
You need to build LLVM with OProfile support enabled.

**Comment by mabl** [comment]
Interesting, I've reported that in the Arch Linux bug tracker. 

Looking at older Arch packages for llvm 3.6, I do not see any specially enabled OProfile support. Any hints what changed in 3.7?

**Comment by pitrou** [comment]
Have you tried compiling llvmlite 0.8 with LLVM 3.6? I think you would run into the same issue.

**Comment by foutrelis** [comment]
The real issue is that llvm-config doesn't include the LLVMOProfileJIT library in its output when LLVM is configured with `-DLLVM_USE_OPROFILE=ON`. (You have filed that bug upstream as https://llvm.org/bugs/show_bug.cgi?id=25091)

Unconditionally adding `-lLLVMOProfileJIT` to LIBS in `ffi/Makefile.linux` breaks when LLVM is not configured with OProfile support (as seen in the comments here). Note that no Linux distro enables OProfile support anyway, so this is not a good workaround to the llvm-config bug.

Based on the above, I believe that linking to LLVMOProfileJIT needs to be made conditional (or simply remove it and wait for a proper upstream fix so llvm-config doesn't omit this library).

**Comment by mabl** [comment]
Hi @foutrelis, thank you for the analysis. Indeed it looks like llvmlite does compile fine when the manually added LLVMOProfileJIT is removed.

**Comment by mabl** [comment]
@pitrou 
I've tried this llvmlite with numba stable and the current master branch. In both cases I ran into

```
Traceback (most recent call last):
  File "/home/mabl/PhD/Software/dlwControl2/dlwControl2/tools/misc/local_reduced_power.py", line 3, in <module>
    import numba
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/__init__.py", line 7, in <module>
    from . import testing, decorators
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/decorators.py", line 9, in <module>
    from .targets import registry
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/targets/registry.py", line 11, in <module>
    class CPUTarget(TargetDescriptor):
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/targets/registry.py", line 14, in CPUTarget
    target_context = cpu.CPUContext(typing_context)
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/targets/base.py", line 181, in __init__
    self.init()
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/targets/cpu.py", line 43, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/targets/codegen.py", line 392, in __init__
    self._init(self._llvm_module)
  File "/home/mabl/PhD/Software/virtualenv/lib/python2.7/site-packages/numba/targets/codegen.py", line 402, in _init
    tli = ll.create_target_library_info(llvm_module.triple)
AttributeError: 'module' object has no attribute 'create_target_library_info'
```
Obviously, because the TargetLibraryInfo was removed by this PR. You mentioned, that numba works fine for you. Do I need any other numba version than that?  _tli is also used inside numba, setting it to None does not help.

**Comment by pitrou** [comment]
When I said Numba works fine, I meant after having done the necessary API changes. Needless to say that this PR is not yet ready for merging (hence the "WIP").

**Comment by Maher4Ever** [comment]
@pitrou is there an update on the readiness of this PR? It would be awesome to have this merged as a lot of tools using LLVM have upgraded to 3.7.

**Comment by seibert** [comment]
LLVM 3.7.1 was released a few days ago, including an API/ABI change (actually, reverting a change in 3.7.0), so I think this PR will need to be tested against that.

We typically update do major LLVM upgrades after the x.y.1 release comes out, based on previous experience with bugs in x.y.0 releases.

**Comment by pitrou** [comment]
Another criterion for us is whether Numba can be easily migrated, since CUDA support uses a separate toolchain (NVidia's  `nvvm`), and the IR changes significantly between 3.6 and 3.7.

**Comment by seibert** [comment]
Right.  I think we will be looking at that issue for the February release.

**Comment by pitrou** [comment]
Another possibility for us is to wait for 3.8.x, since the IR changes in 3.7 are transitional and the work on the untyped pointer transition is not finished yet.

**Comment by pitrou** [comment]
I've checked that this branch still runs with 3.7.1, by the way.

**Comment by seibert** [comment]
We might have no choice but to face the issue, since it sounds like the AMD fork of LLVM for HSA devices will be using the version 3.7 IR syntax.  Hopefully a registered-developer release of CUDA 8 will come out soon, and then we can see which way NVVM will be going in the near future.

**Comment by Maher4Ever** [comment]
Thank you both for the responses. Are you aware of any tools that convert LLVM syntax from 3.6 to 3.7? I would like to use the LLVM IR generated by numba with Emscripten to generate JS from Python. Emscripten unfortunately doesn't support the 3.6 syntax. Only the 3.5 and 3.7 syntax for some reason.

**Comment by pitrou** [comment]
LLVM bitcode (not IR) format is supposed to be portable between versions, so you can try using that.

**Comment by Maher4Ever** [comment]
@pitrou Ok thank you. I'll try using the bitcode.

**Comment by mabl** [comment]
@pitrou I just wanted to say, that this worked flawlessly together with the numba patches of you. The only thing I needed to do was patch the hardcoded reference to LLVMOProfileJIT away.

**Comment by pitrou** [comment]
> The only thing I needed to do was patch the hardcoded reference to LLVMOProfileJIT away.

Thanks for the feedback! I'll check whether the hardcoded reference is still needed.

**Comment by pitrou** [comment]
Unfortunately, the hardcoded reference to LLVMOProfileJIT still seems necessary here.

**Comment by mabl** [comment]
Hi @pitrou, as far as I understand the LLVM_USE_OPROFILE dependency is new with your patch right? You've also changed the Linux conda build to include it (but not osx?). Is there a theoretical chance to avoid depending on a compiler with this option enabled?

When I'm back in the office tomorrow I'll try to test the unittest with an llvmlite build without being linked against LLVMOProfileJIT (at least my simple numba stuff worked flawlessly already).

**Comment by pitrou** [comment]
> as far as I understand the LLVM_USE_OPROFILE dependency is new with your patch right?

No, OProfile support was already part of Linux builds before.

> You've also changed the Linux conda build to include it (but not osx?).

OProfile is a Linux-specific functionality, so unavailable on OSX and other platforms.

> Is there a theoretical chance to avoid depending on a compiler with this option enabled?

OProfile doesn't require a specific compiler. You just need to have the right development headers installed for compiling. There is no runtime dependency that I know of, until you actually use the functionality.

**Comment by Maher4Ever** [comment]
Awesome :+1:

**Comment by Alisa-lisa** [comment]
So why exactly is there a hard link time dependency on OProfile? It does fail on Arch Linux and I suppose perhaps other distros as well. It does seem to compile fine without. I suggest making OProfile optional depending on library availability.

**Comment by pitrou** [comment]
> So why exactly is there a hard link time dependency on OProfile?

Because it's much easier for us to manage. I'd rather not introduce a conditional compilation machinery. I'm surprised it wouldn't work on Arch Linux, does Arch Linux not provide the opagent.h header file?

**Comment by foutrelis** [comment]
I have explained what the issue with that library include is in https://github.com/numba/llvmlite/pull/100#issuecomment-160850386.

**Comment by pitrou** [comment]
Several things here:
- llvmlite's build system is not meant to be all-purpose; it's tailored for our needs which means 1) production of binary conda packages 2) ease of local development
- Maintaining a general-purpose, flexible, portable build system is a daunting task, as many projects know
- I'd like the llvm-config bugs to be resolved as much as anyone else; unfortunately I don't know how to make sure it happens (but perhaps you can voice your support on that issue)
- If distros don't enable oprofile support in their LLVM builds, perhaps they should :-) there is no downside that I know of

**Comment by seibert** [comment]
That said, llvmlite is being used more and more on differently configured systems, and so I would like to see if we can accommodate common build configuration issues.  Is there a workaround we can use until llvm-config is fixed?

This is made more problematic by all the different ways that LLVM can be built.  We seldom have success with the LLVM compiled by the user's Linux distro (yet another reason we statically link llvmlite to LLVM to avoid depending on the system LLVM).

**Pull request merged**
