### PR TITLE
Fix store to opaque ptr

### PR DESCRIPTION
**Pull request by alexander-shaposhnikov**
If ptr.type.is_opaque is True it doesn't need to have ptr.type.pointee attribute.
Add a unit test.

### CODE REVIEW

**Comment by rj-jesus** [comment]
@sklam Yep, sure.
Thanks for the patch, @alexander-shaposhnikov.
In general it LGTM, my only comment would be that the new test `test_store` could maybe be part of `test_mem_ops`, but I don't think this is critical.

**Comment by alexander-shaposhnikov** [comment]
Many thanks, I've updated the PR.

**Review by rj-jesus — COMMENTED** [review]
Thanks very much, LGTM!
(@sklam I can't approve it myself.)

**Comment by alexander-shaposhnikov** [comment]
@sklam (would be amazing if you could merge this in, many thanks in advance)

**Review by gmarkall — APPROVED** [review]

**Pull request merged**
