### PR TITLE
Add support for compiler-rt inclusion

### PR DESCRIPTION
**Pull request by testhound**
This pull request adds support for including compiler-rt as a artifact. It is meant to address this outstanding issue:
https://github.com/numba/llvmlite/issues/834

### CODE REVIEW

**Comment by sklam** [comment]
Developer Note: 

This PR depends on merging LLVM14 changes.

**Comment by sklam** [comment]
From OOB discussion, the OSX build failure is depending on https://github.com/conda/conda-build/issues/4787 to successfully build compiler-rt

**Comment by testhound** [comment]
@sklam and @gmarkall ready for review after adding support for llvm 14. Note that there are several places where I was forced to iinstall llvmdev from my channel because it includes compiler-rt. 

For example: "call conda install -y -q --override-channels -c mcollison llvmdev="14.*"

**Comment by testhound** [comment]
@sklam and @gmarkall: all buildfarm tests now pass, ready for review.

**Comment by testhound** [comment]
@sklam and @gmarkall I had to modify conda build locally to allow creating a MacOS llvmdev package like this:

`diff --git a/conda_build/os_utils/pyldd.py b/conda_build/os_utils/pyldd.py
index efce517c..d819bade 100644
--- a/conda_build/os_utils/pyldd.py
+++ b/conda_build/os_utils/pyldd.py
@@ -1024,6 +1024,11 @@ def codefile_class(filename, skip_symlinks=False):
     # Java .class files share 0xCAFEBABE with Mach-O FAT_MAGIC.
     if filename.endswith('.class'):
         return None
+    # lief does not (yet) support querying for static libraries;
+    # this used to silently work but surfaced by lief 0.12, see
+    # https://github.com/lief-project/LIEF/issues/873
+    if filename.endswith('.a'):
+        return None
     if not os.path.exists(filename) or os.path.getsize(filename) < 4:
         return None
     with open(filename, 'rb') as file:`

**Comment by testhound** [comment]
@sklam and @gmarkall I had to modify conda build locally as described by the last comment here:

https://github.com/conda/conda-build/pull/4808

**Comment by testhound** [comment]
@sklam and @gmarkall I resolved the merge conflicts and remove support for LLVM 11.

**Comment by sklam** [comment]
@esc, please consider this and related PR for inclusion of the upcoming llvmlite release.

**Comment by esc** [comment]
> @esc, please consider this and related PR for inclusion of the upcoming llvmlite release.

Thank you, added to the milestone.

**Comment by oliverhu** [comment]
@testhound I followed this PR, and it seems `libclang_rt` is not statically linked into `llvmlite.so`, not sure if that is intended or not. btw, shall we add tests to validate this works in both native bfloat architecture & non-native bfloat architecture?

**Comment by gmarkall** [comment]
@oliverhu This PR is not being worked on by @testhound anymore, and needs someone to pick it up and continue it - eventually someone working on Numba / llvmlite may get round to it, but it could take some time - do you have any interest in attempting to adopt this PR and working on it? I'm happy whether you are or aren't - just let me know if you are and we can figure out some steps to move this forward.

**Comment by oliverhu** [comment]
@gmarkall thanks! happy to help here...the only concern is I'm new to this project (got a crash from https://github.com/tinygrad/tinygrad/issues/1367 so I hunted all the way down here). I might not have the full context besides the issue I was impacted. Is there a channel (slack/discord) to discuss questions? back-n-forth in GitHub is not the most effective way!

**Comment by gmarkall** [comment]
@oliverhu There's the Numba Gitter (https://matrix.to/#/#numba_numba:gitter.im) - I'm usually around there during UK office hours (it's 11pm here but I can discuss this interactively tomorrow).

**Comment by oliverhu** [comment]
Sounds good, will reach out on gitter!

**Comment by gmarkall** [comment]
Superseded by #986 / #1036, etc.

**Pull request closed without merging**
