### PR TITLE
Support profiing with OProfile

### PR DESCRIPTION
**Pull request by markdewing**
Add the OProfile JIT event listener to allow the JIT'ed code
to be analyzed with a hardware profiler on Linux.

To enable this code:
 - enable LLVM for OProfile JIT events (-DLLVM_USE_OPROFILE=ON)
 - define USE_OPROFILE_JITEVENTS when compiling llvmlite
 - define environment variable ENABLE_JITPROFILING
 - LD_LIBRARY_PATH may need to point to the directory containing
        libopagent.so (/usr/lib/oprofile)

Tested with LLVM 3.6

Annotating assembly works (with opannotate), but I think debug information will be needed to annotate source (see issue #10 )

### CODE REVIEW

**Comment by pitrou** [comment]
Oh, thank you for doing this. Do you think it's possible to have a Python API to enable profiling, rather than an environment variable? Also, does it also work with Linux `perf`?

**Comment by markdewing** [comment]
I will look into making a Python API instead.

The `perf` tool does have a simple JIT interface, but I think it would require some support in LLVM to write the proper file.

**Comment by markdewing** [comment]
Updated with a potential Python API.

**Comment by pitrou** [comment]
Thanks. The API looks good enough for now. For Linux perf it may be possible to write a specific event listener class to write the specific file (Mesa does this which looks rather hackish: http://lists.freedesktop.org/archives/mesa-commit/2013-April/042805.html).

**Pull request merged**
