### PR TITLE
Aarch64 split build for LLVM14

### PR DESCRIPTION
**Pull request by sklam**

### CODE REVIEW

**Comment by sklam** [comment]
https://github.com/numba/llvmlite/pull/910/commits/0a300974bdfdc182a5de02a61728aee116650eb8: I made sure that git history from current llvm11 files are retained

**Comment by sklam** [comment]
Merged in #830 to fix CI

**Comment by sklam** [comment]
pass BFID: `llvmdev_73`

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. On inspection, this seems to split out the `llvmdev` builds such that on `linux-aarch64` `conda build` will build `llvmdev` based on version 11.x and on other OS/architectures it will build based on version 14.x. This to help work around issues such as https://github.com/numba/numba/issues/8738.

I've checked the logs for the referenced buildfarm run of this patch and the correct LLVM versions appear to have been built on the expected platforms as described above.

Thanks also for making the minor changes to `test_refprune.py` and `ffi/Makefile.osx` as discussed OOB. That the public CI testing of the former passed suggests it is fine, all that remains is a rebuild of the OSX packages to pick up the change from `-O3` to `-O2` following merge.

Thanks again for working on this.

**Pull request merged**
