### PR TITLE
Remove python 2, python < 3.6, fix up, add flake8

### PR DESCRIPTION
**Pull request by stuartarchibald**
This PR:
* Removes Python 2 specific code.
* Removes Python <3.6 specific code.
* Removes build/test infrastructure relating to the above.
* Adds build/test infrastructure for Python 3.8
* Adds `flake8` checks to the source and enforces this in CI.
* Fixes up the code base to be flake8 compliant.
* Remove the `AUTHORS` file, this information is in `git` and the `CHANGE_LOG`
* Fixes up the documentation (to some degree, LLVM 9 changes pending).

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Anticipate CI fails will need https://github.com/numba/llvmlite/pull/554 merging, and then a rerun.

**Comment by stuartarchibald** [comment]
CI passed and @sklam approves. Marking for merge.

**Comment by ARF1** [comment]
@stuartarchibald @sklam Bumping to python <= 3.6 did not take for the AppVeyor:

```
C:\projects\llvmlite>conda create -n testenv -q -y python=3.8 cmake 
Fetching package metadata .......
Solving package specifications: .
Error: Package missing in current win-64 channels: 
  - python 3.8*
```

The result is that the AppVeyor CI build falls back to python 3.5 which means that any PR that uses python 3.6 features fails. For an example see #564.

Would it be acceptable to set python to 3.6 instead of python 3.8 for AppVeyor? If yes, #565 does this.

**Pull request merged**
