### PR TITLE
manylinux2014 aarch64 wheels with system compilers

### PR DESCRIPTION
**Pull request by esc**
As title

### CODE REVIEW

**Comment by esc** [comment]
I managed to build a `linux-aarch64` `llvmdev` package for `manylinux2014` using the system compilers and w/o adding `python` as a dependency

```
 💣 zsh» CONDA_SUBDIR=linux-aarch64 conda search -c esc/label/manylinux2014 llvmdev=11.1.0 --info        
Loading channels: done
llvmdev 11.1.0 manylinux2014
----------------------------
file name   : llvmdev-11.1.0-manylinux2014.tar.bz2
name        : llvmdev
version     : 11.1.0
build       : manylinux2014
build number: 2
size        : 341.0 MB
license     : NCSA
subdir      : linux-aarch64
url         : https://conda.anaconda.org/esc/label/manylinux2014/linux-aarch64/llvmdev-11.1.0-manylinux2014.tar.bz2
md5         : 5eebd168d89159bee9ed47762eafa80f
timestamp   : 2021-07-22 15:06:53 UTC
dependencies: []
```

**Comment by esc** [comment]
Using this `llvmdev` package I now compiled a bunch of resulting llvmlite wheels, which can be found at:

https://anaconda.org/numba/llvmlite/files?channel=manylinux2014_testing_wheels_02

**Comment by esc** [comment]
Since the conda package was fine and the wheels were fine too, I think, what should be done:

a) Move/copy the package from `esc/label/manylinux2014` to `numba/label/manylinux`
b) Revert the final two commits on this branch and merge it to `master`
c) Cherry-pick to the `release0.37` branch and use it to buildout the wheels for RC3

@sklam do you agree?

**Comment by sklam** [comment]
Yes, sounds like a plan. Thanks!

**Comment by esc** [comment]
> a) Move/copy the package from `esc/label/manylinux2014` to `numba/label/manylinux`

Done.

> b) Revert the final two commits on this branch and merge it to `master`

And Done.

Think this is ready for merge!

**Comment by gmarkall** [comment]
I can confirm that the aarch64 package appears to have no dependencies:

```
$ CONDA_SUBDIR=linux-aarch64 conda search -c numba/label/manylinux2014 llvmdev=11.1.0 --info
Loading channels: done
llvmdev 11.1.0 manylinux2014
----------------------------
file name   : llvmdev-11.1.0-manylinux2014.tar.bz2
name        : llvmdev
version     : 11.1.0
build       : manylinux2014
build number: 2
size        : 341.0 MB
license     : NCSA
subdir      : linux-aarch64
url         : https://conda.anaconda.org/numba/label/manylinux2014/linux-aarch64/llvmdev-11.1.0-manylinux2014.tar.bz2
md5         : 5eebd168d89159bee9ed47762eafa80f
timestamp   : 2021-07-22 15:06:53 UTC
dependencies: []
```

**Comment by gmarkall** [comment]
Whoops, that was an accident running CI here. Apologies (hopefully all will still be green anyway :-) )

**Comment by gmarkall** [comment]
@sklam Can you confirm that this is ready to merge?

**Comment by gmarkall** [comment]
> Whoops, that was an accident running CI here. Apologies (hopefully all will still be green anyway :-) )

OK, so it's not green because of the Python 3.10 issue - however, it's irrelevant for this PR since it only modifies the manylinux2014 wheel scripts.

**Review by sklam — APPROVED** [review]
Yup, looks like it is ready

**Comment by esc** [comment]
@sklam @gmarkall thank you for the review!

**Pull request merged**
