### PR TITLE
add support for more constant expressions

### PR DESCRIPTION
**Pull request by john-tornblom**
This is an initial PR to clarify preferred design decisions before I commit more time and effort, expect more commits based on feedback before a potential merge.

1. Is the use of a decorator called _binop appropriate? It is somewhat copy&paste from builder.py
2. Is the naming scheme "lhs" and "rhs" in docstrings OK, even though they do not match argument list?
3. is the testing approach appropriate, i.e., string compare of emitted llvm-ir?

### CODE REVIEW

**Comment by esc** [comment]
@john-tornblom thank you for submitting this. I have labelled it accordingly. Please note that we are currently in a release candidate phase, so it may be some time before your PR becomes reviewed and merged.

**Comment by gmarkall** [comment]
Looks like I don't yet have the rights to re-run CI - the failure looks to have been a conda HTTP failure though.

**Comment by esc** [comment]
@gmarkall I am looking into giving you the correct permissions, but for now I have triggerd public-ci for you.

**Comment by gmarkall** [comment]
Not sure why CI still isn't running, but I guess this is ready for review so I've marked it as such. I haven't properly reviewed it (just a skim) but my thoughts on your questions are:


> Is the use of a decorator called _binop appropriate? It is somewhat copy&paste from builder.py

I think this is fine.

> Is the naming scheme "lhs" and "rhs" in docstrings OK, even though they do not match argument list?

I think this makes sense - it makes the docstring more sensible, which I think is better than rigidly conforming to any perceived "standard".

> is the testing approach appropriate, i.e., string compare of emitted llvm-ir?

This looks good to me, and is the approach taken for a lot of the tests. I assume you are planning on adding other tests to cover the other operations?

**Comment by esc** [comment]
I think AZP was lagging a bit today.

**Comment by gmarkall** [comment]
@john-tornblom Is this now ready for a review, or do you plan to make further changes?

**Comment by john-tornblom** [comment]
I have no more changes planned, so I believe this is ready for review now.

**Comment by john-tornblom** [comment]
I rebased against master and added more casting operations. I currently have no more planned contributions.

**Comment by gmarkall** [comment]
@john-tornblom Many thanks - I've added it to the 0.38 (next release) milestone.

**Comment by esc** [comment]
@john-tornblom would you be able to rebase this again. It seems like there are now more conflicts.

**Comment by gmarkall** [comment]
> @john-tornblom would you be able to rebase this again. It seems like there are now more conflicts.

@john-tornblom Apologies for the clarification - could you merge master rather than rebasing please? (this is just a general policy request as rebases confuse Github's review tracking somewhat making it harder to keep track of updates on the reviewing side)

**Comment by gmarkall** [comment]
Branch with merge and conflicts resolved is now pushed to https://github.com/gmarkall/llvmlite/tree/pr-735 - tests pass locally for me with this.

In resolving conflicts, I thought something might be amiss with the test and message for `ptrtoint` - see https://github.com/numba/llvmlite/pull/784/files#r755539202

@esc if the resolved version looks good, would you mind pushing it as I don't have write access to llvmlite please?

**Review by gmarkall — CHANGES_REQUESTED** [review]
After merging master and resolving conflicts, I think this looks basically good.

- Expressions are consistent with the builder interfaces
- Docstrings seem to be accurate
- Each new function is tested and the test makes sense
- I also checked that each expression will actually parse, so the strings that are expected in the tests are valid.
- Implementation looks good.

The only issue is that the new expressions don't show up in the docs for `Constant` and `GlobalValue`, because those docs are not autogenerated from the docstrings (https://llvmlite--735.org.readthedocs.build/en/735/user-guide/ir/values.html) so some additional change to the documentation is needed to mention that these are available.

**Comment by stuartarchibald** [comment]
@gmarkall RE: 
> In resolving conflicts, I thought something might be amiss with the test and message for ptrtoint - see https://github.com/numba/llvmlite/pull/784/files#r755539202

Fixed in https://github.com/numba/llvmlite/pull/794

**Comment by gmarkall** [comment]
Continued in #795 with master merged in and documentation added.

**Comment by esc** [comment]
@gmarkall thank you for the notice, will close this now.

**Pull request closed without merging**
