### PR TITLE
targets.py: Add ABIName parameter for RISC-V hard float targets

### PR DESCRIPTION
**Pull request by occheung**
LLVM requires RISC-V targets to specify ABI if hard float is supported. The current implementation does not allow `TargetOptions.McOptions.ABIName` to be specified.

This patch exposes the ABIName to the `create_target_machine` function. So a RISC-V target that supports hard-float can be created like such:
```
        lltarget = llvm.Target.from_triple("riscv32-unknown-linux")
        llmachine = lltarget.create_target_machine(
                        features="+m,+a,+f,+d",
                        reloc="pic", codemodel="default", abiname="ilp32d")
```
Similar feature was also added to Rust's LLVM interface: [See discussion](https://github.com/rust-lang/rust/issues/65024) | [See commit](https://github.com/rust-lang/rust/commit/539de439ad6f32e9a9a8a593299072a106786890)

Alternatively, we can also process the target triple and features to deduce the appropriate ABI.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
Can we get this merged? Sounds like a simple change.

**Comment by esc** [comment]
> Can we get this merged? Sounds like a simple and valid change.

@sbourdeauducq I think the problem is that access to RISC-V is limited. Have you been able to test this on some real hardware?

**Comment by gmarkall** [comment]
I can test this - will post an update once I've done so.

**Comment by sbourdeauducq** [comment]
> Have you been able to test this on some real hardware?

Definitely - our compiler uses llvmlite with the patch and we test it on our FPGA board, we even have hardware-in-the-loop CI.

**Comment by gmarkall** [comment]
@sbourdeauducq How are you building and testing this? Are you building an llvmlite with the RISCV target enabled?

**Comment by sbourdeauducq** [comment]
If you meant LLVM with the RISCV target enabled - yes.

**Comment by gmarkall** [comment]
Thanks... I was originally going about testing this the wrong way - I was building on a RISC-V host and trying to find a way to get the LLVM JIT to work so the whole test suite could run - I've not completed testing this PR yet but haven't forgotten it.

**Comment by sbourdeauducq** [comment]
If you don't have any hardware to test, QEMU can emulate RISC-V. Or just looking at the generated assembly should be enough anyway.

**Comment by gmarkall** [comment]
In that case, is it possible to add a test that can run on the host with a RISC-V target that can check for the expected output in the generated assembly? That would make it a lot easier to check that I'm checking this PR correctly (and also lay a good foundation for future RISC-V-specific code generation functionality and tests).

**Comment by seibert** [comment]
#785 is related, as we will want to add RISCV as a target in our LLVM builds in order to run any RISC-V tests in our CI systems.

**Comment by occheung** [comment]
> In that case, is it possible to add a test that can run on the host with a RISC-V target that can check for the expected output in the generated assembly?

Tests regarding the impact of ABI are performed in LLVM already, such as [this](https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/RISCV/calling-conv-vector-float.ll) (albeit in later LLVM version).

AFAIK the ABIs should have no influence on how the LLVM IR needs be written?

**Comment by sbourdeauducq** [comment]
> AFAIK the ABIs should have no influence on how the LLVM IR needs be written?

Yes.
The only thing that can be tested here is that when the ABI option is set from the high-level Python code, the assembly (machine, not IR) code generated at the end by LLVM is affected appropriately.

**Comment by gmarkall** [comment]
Many thanks for adding the tests! I think that you have found the correct location to modify, but I'm not sure if there's additional places it would need modifying too - I will check.

**Comment by gmarkall** [comment]
There's also https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/bld.bat#L10 and https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/build.sh#L8 to modify as well.

**Comment by gmarkall** [comment]
Many thanks for adding the RISCV target - note that this will need the llvmdev / llvmlite packages to be rebuilt on our channel before the test starts to pass in CI.

**Comment by esc** [comment]
@gmarkall thank you for tending to this PR. We will need to decide what llvmlite version this should be a part of.

**Comment by sbourdeauducq** [comment]
From our perspective we would really appreciate a Conda Win64 package with RISC-V, this, and https://github.com/numba/llvmlite/pull/702.
It's easy to have patches on our Hydra CI server and NixOS machines, but for Windows it's a very different story.

**Review by gmarkall — CHANGES_REQUESTED** [review]
This generally looks good to me. Some notes:

* WIth #788, the tests passed. :tada: 
* I was a little concerned about fragility of the test because it checks the assembly strings line-for-line, but on reflection I don't think they are likely to change unless we upgrade LLVM, so they will likely be stable enough in their current form.
* The documentation in `docs/source/user-guide/binding/target-information.rst` will also need updating, as it isn't generated from the docstring.

**Comment by gmarkall** [comment]
@occheung Many thanks for updating the docs!

A side note: could I please ask that for future changes you merge master rather than rebasing please? The reason for this is that Github doesn't make it easy to track what happened on the reviewing side in newly-added commits. I *think* the only substantive change in your last push is the addition of the docs, but it's quite hard for me to tell for certain. Many thanks in advance!

**Review by gmarkall — APPROVED** [review]
This looks good to me, assuming that CI passes after new packages have been built following the merge of #788.

**Comment by esc** [comment]
@gmarkall it looks like this is still bust

**Comment by gmarkall** [comment]
@esc Let's discuss this a little in the dev meeting if there's time.

**Comment by stuartarchibald** [comment]
Is the issue that the build scripts are looking in channel `numba` and picking up build 3:
https://github.com/numba/llvmlite/blob/master/buildscripts/incremental/setup_conda_environment.sh#L30
Log extract:
```
2021-11-23T12:23:01.4828781Z   added / updated specs:
2021-11-23T12:23:01.4830437Z     - llvmdev=11
2021-11-23T12:23:01.4830913Z 
2021-11-23T12:23:01.4831264Z 
2021-11-23T12:23:01.4831844Z The following packages will be downloaded:
2021-11-23T12:23:01.4832287Z 
2021-11-23T12:23:01.4832844Z     package                    |            build
2021-11-23T12:23:01.4833699Z     ---------------------------|-----------------
2021-11-23T12:23:01.4834640Z     llvmdev-11.1.0             |       he1b5a44_3       374.3 MB  numba
2021-11-23T12:23:01.4835592Z     ------------------------------------------------------------
2021-11-23T12:23:01.4836332Z                                            Total:       374.3 MB
2021-11-23T12:23:01.4836829Z 
2021-11-23T12:23:01.4837394Z The following NEW packages will be INSTALLED:
2021-11-23T12:23:01.4837907Z 
2021-11-23T12:23:01.4838694Z   llvmdev            numba/linux-64::llvmdev-11.1.0-he1b5a44_3
```
whereas it's build 4 that contains the additional cross targets and they are all in `numba/label/ci` ?

**Comment by esc** [comment]
> Is the issue that the build scripts are looking in channel `numba` and picking up build 3: https://github.com/numba/llvmlite/blob/master/buildscripts/incremental/setup_conda_environment.sh#L30 Log extract:
> 
> ```
> 2021-11-23T12:23:01.4828781Z   added / updated specs:
> 2021-11-23T12:23:01.4830437Z     - llvmdev=11
> 2021-11-23T12:23:01.4830913Z 
> 2021-11-23T12:23:01.4831264Z 
> 2021-11-23T12:23:01.4831844Z The following packages will be downloaded:
> 2021-11-23T12:23:01.4832287Z 
> 2021-11-23T12:23:01.4832844Z     package                    |            build
> 2021-11-23T12:23:01.4833699Z     ---------------------------|-----------------
> 2021-11-23T12:23:01.4834640Z     llvmdev-11.1.0             |       he1b5a44_3       374.3 MB  numba
> 2021-11-23T12:23:01.4835592Z     ------------------------------------------------------------
> 2021-11-23T12:23:01.4836332Z                                            Total:       374.3 MB
> 2021-11-23T12:23:01.4836829Z 
> 2021-11-23T12:23:01.4837394Z The following NEW packages will be INSTALLED:
> 2021-11-23T12:23:01.4837907Z 
> 2021-11-23T12:23:01.4838694Z   llvmdev            numba/linux-64::llvmdev-11.1.0-he1b5a44_3
> ```
> 
> whereas it's build 4 that contains the additional cross targets and they are all in `numba/label/ci` ?

good catch, that may very well be the case!

**Comment by gmarkall** [comment]
All tests passed now that the llvmdev packages are available on the main channel - many thanks @esc!

**Comment by esc** [comment]
> All tests passed now that the llvmdev packages are available on the main channel - many thanks @esc!

👌 Excellent!

**Comment by esc** [comment]
@occheung @sbourdeauducq @gmarkall thank you all!

**Pull request merged**
