### PR TITLE
Move to LLVM 7

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

* Bumps llvmdev to LLVM 7.

  * Adjusts patches and applies those from @anton-malakhov as per:
    https://github.com/conda-forge/llvmdev-feedstock/pull/47
  * Removes dead patches
  * Removes build forking for PPC64LE

* Updates llvmlite internals and docs reflect the version changes.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
CI will need an `llvmdev==7.x` build pushing to anaconda.org for it to have a chance of passing.

**Comment by anton-malakhov** [comment]
If you want to fork/merge recipe from https://github.com/conda-forge/llvmdev-feedstock, please add that the second part of the merged patch is published as https://reviews.llvm.org/D53035 (the first part is referred in the patch file already)

**Comment by stuartarchibald** [comment]
RE: https://github.com/numba/llvmlite/pull/404#issuecomment-431162024 thanks, I'll note that in the `meta.yaml` at the point of patch inclusion.

**Comment by stuartarchibald** [comment]
@anton-malakhov comment added in 0192016

**Pull request merged**
