### PR TITLE
bump llvmdev to 11

### PR DESCRIPTION
**Pull request by esc**
As it is now passing everywhere else, we upgrade public CI now too.

### CODE REVIEW

**Comment by esc** [comment]
I have moved the llvmdev 11 build 2 packages to `numba/label/main` and now everything is well.

**Comment by esc** [comment]
the RTD build apparently completed:

https://readthedocs.org/projects/llvmlite/builds/14087364/

But the status was not communicated back to github, so this PR, looks like it is hanging.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Pull request merged**
