### PR TITLE
Make tests that require cross compilation to RISCV optional.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This makes the tests for the RISCV target ABI name only execute if
the linked LLVM supports compilation (host or cross) to the RISCV
target.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Suggestion for testing this: Build this with this PR and llvmdev build 3 from the numba conda channel, the tests named `"*test_rv32d_ilp32*"` should skip, then do the same but with build 4 and the same tests should pass.

**Comment by esc** [comment]
With build 3:

```
 💣 zsh» python llvmlite/tests/test_binding.py -v |& grep skipped                                                                                                                                                                                           :(
test_linux (__main__.TestDependencies) ... skipped 'Linux-specific test'
test_rv32d_ilp32 (__main__.TestRISCVABI) ... skipped 'RISCV target unsupported by linked LLVM.'
test_rv32d_ilp32d (__main__.TestRISCVABI) ... skipped 'RISCV target unsupported by linked LLVM.'
test_rv32d_ilp32f (__main__.TestRISCVABI) ... skipped 'RISCV target unsupported by linked LLVM.'
OK (skipped=4)
```

**Comment by esc** [comment]
With build 4:

```
 💣 zsh» python llvmlite/tests/test_binding.py -v |& grep skipped
test_linux (__main__.TestDependencies) ... skipped 'Linux-specific test'
OK (skipped=1)
```

**Review by esc — APPROVED** [review]
LGMT!

**Pull request merged**
