### PR TITLE
Revert "Revert "LLVM 7 changed memset intrinsic signature, adjust it""

### PR DESCRIPTION
**Pull request by sklam**
Reverts numba/llvmlite#484

### CODE REVIEW

**Comment by seibert** [comment]
Given the issues we had with Numba failing after this PR, are we also going to break other users of llvmlite if we make this change?

**Comment by sklam** [comment]
Yes, this is a breaking change.

**Comment by seibert** [comment]
I think we're now big enough that we have to go through the deprecation process then.  We can start that in the 0.30 dev cycle.

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/llvmlite/pull/511, deprecation notice issued.

**Comment by stuartarchibald** [comment]
Corresponding doc update for 0.31 noting removal. https://github.com/numba/llvmlite/pull/533

**Pull request merged**
