### PR TITLE
Add initial NetBSD support

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by pitrou** [comment]
Hi, and thanks for the PR. Beware that we don't have any machines running NetBSD for CI, so you'll have to track changes and make sure NetBSD support doesn't get broken. Is that ok for you?

**Comment by krytarowski** [comment]
What we need to do to add NetBSD machines to CI?

**Comment by seibert** [comment]
Are there any public CI systems (like Travis-CI) that offer NetBSD workers?

**Comment by krytarowski** [comment]
Hosted for GitHub - I don't think so. I'm running LLVM buildbot on a private server.

**Comment by pitrou** [comment]
So I guess you'll have to track any possible breakage yourself. If that's ok to you we can merge the PR :-)

**Comment by krytarowski** [comment]
It's fine.

**Comment by stuartarchibald** [comment]
Closing as this PR is stale with respect to current LLVM builds. To enable `netbsd` support I think an addition similar to that present in https://github.com/numba/llvmlite/pull/356 would be all that is needed in the current code base (v0.25.x). Thanks.

**Comment by krytarowski** [comment]
The PR is not stale on my side so please reopen.

**Comment by krytarowski** [comment]
I will rebase my patch for a newer version (I will get back home next week).

**Pull request closed without merging**
