### PR TITLE
Port refprune pass to NewPassManager

### PR DESCRIPTION
**Pull request by yashssh**
Based on the changes introduced in #1042 by @modiking

### CODE REVIEW

**Comment by yashssh** [comment]
Please just review the last commit as it is rebased on top of #1046

**Comment by dlee992** [comment]
I "checked" the last commit. LGTM. only has some minor format issues, but I feel don't need to bring it up. 
Also learned the difference of how to add a pass for old and new pass managers. Nice.

**Comment by modiking** [comment]
LGTM

**Comment by yashssh** [comment]
Rebased

**Comment by yashssh** [comment]
Clang format does not report anything for me locally. What version of clang-format is used in the checks?

**Comment by yashssh** [comment]
I missed to update `test_refprune.py` and there might be some complications there. Consider this "not yet ready for review" for now. 
Thanks :)

**Comment by gmarkall** [comment]
> Clang format does not report anything for me locally. What version of clang-format is used in the checks?

It is clang-format-14, I think.

**Comment by yashssh** [comment]
Gentle ping

**Review by yashssh — COMMENTED** [review]
I have added some inline comments to make the thought process behind the the changes more apparent to the reviewers. 

The gist of the changes are:
1) We prefix the old refprune passes with legacy keyword.
2) We create a new refprune pass following the new pass manager syntax.
3) Now that we have multiple instances of the same pass, to prevent duplication of code we move the computation functions to a more global scope(struct) so that both passes can share them.

Found this article online which comes very close to explaining what we did here https://www.neilhenning.dev/posts/llvm-new-pass-manager/

Examples from llvm codebase on porting a pass to NPM 

- https://github.com/yashssh/llvm-project/commit/f5080194fda520cb67334165582aadfb413f3d22
- https://reviews.llvm.org/D22703

**Review by gmarkall — CHANGES_REQUESTED** [review]
Thanks for the PR - the code changes look good, and I was able to follow them well from the info you provided / linked to. I think there are two things that need adding:

- Documentation for the `add_refprune_pass` functions of the new module and function pass managers
- Keep the tests for the legacy pass manager, as well as testing with the new pass manager. Although there's a low probability of issues with the legacy pass manager, the changes do touch their code (and other future changes might potentially as well, we never know) so keeping both paths in use tested is important.

**Comment by yashssh** [comment]
Thanks for the review @gmarkall! I have addressed the comments.

**Review by gmarkall — DISMISSED** [review]
Thanks for the additions - I think this is now good to merge!

**Comment by esc** [comment]
@yashssh @gmarkall code needs a fix, it's become conflicting with `main` due to recent merges.  🙏

**Comment by yashssh** [comment]
Resolved now, thanks!

**Comment by esc** [comment]
> Resolved now, thanks!

@yashssh thank your for the swift update! -- @gmarkall can you check this and approve the fixes?

**Comment by yashssh** [comment]
Ping

**Review by gmarkall — APPROVED** [review]
The fixup looks good to me.

**Comment by esc** [comment]
Thank you for the patch!

**Pull request merged**
