### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by sklam**
* Show last update date (#464).
* Auto update docs version.

### CODE REVIEW

**Comment by seibert** [comment]
This blows up Azure, because it doesn't install llvmlite before testing the doc build.  (Does rtd install first?)

**Comment by sklam** [comment]
Patched.  Also tested rendering on https://llvmlite.readthedocs.io/en/rtd_testing/.

**Comment by pfalcon** [comment]
If this causes issues/concerns, then I'd suggest to at least split into a separate PR and merge the "Show last update date in docs" commit, which should be harmless, and which should pretty much address the concern of https://github.com/numba/llvmlite/issues/464.

**Comment by stuartarchibald** [comment]
@seibert @sklam is this good to go now? Seems like all the review issues were addressed?

**Comment by seibert** [comment]
Yeah, I think this is ready to merge.

**Comment by stuartarchibald** [comment]
Thanks @seibert

**Pull request merged**
