### PR TITLE
buildscripts: Unpin wheel

### PR DESCRIPTION
**Pull request by jvesely**
auditwheel has been updated.
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

### CODE REVIEW

**Comment by jvesely** [comment]
ping. this fixes travis CI failures.
anyone interested? @sklam, @stuartarchibald

**Comment by esc** [comment]
@jvesely thanks for submitting this! Am I correct in assuming that this fixes the following issue currently  present on `master`?

```
Traceback (most recent call last):
  File "/opt/python/cp37-cp37m/bin/auditwheel", line 8, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/main.py", line 50, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/main_repair.py", line 49, in execute
    from .repair import repair_wheel
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/repair.py", line 14, in <module>
    from .wheeltools import InWheelCtx, add_platforms
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/wheeltools.py", line 17, in <module>
    from wheel.wheelfile import WHEEL_INFO_RE  # type: ignore
ModuleNotFoundError: No module named 'wheel.wheelfile'
```

**Comment by esc** [comment]
This looks sane and appears to fix build issues, hence I am marking it as ready to merge.

**Comment by jvesely** [comment]
thanks. yes, it should fix the above build breakage on travis

**Pull request merged**
