### PR TITLE
Enable wheel builds

### PR DESCRIPTION
**Pull request by sklam**
* Add a C-extension stub to make bdist_wheel build an arch dependent build

### CODE REVIEW

**Comment by seibert** [comment]
Note that the latest conda build (currently in the conda-canary channel) also has the ability to make wheels.

**Comment by sklam** [comment]
Docs on wheel feature: https://github.com/conda/conda-docs/pull/388

**Comment by sklam** [comment]
I have a linux 64-bit wheel package for testing at 

`pip install -i https://pypi.anaconda.org/sklam/simple llvmlite`

**Comment by sklam** [comment]
I have uploaded new manylinux1 wheels based on the merged branch of this PR to v0.16.0.

**Pull request merged**
