### PR TITLE
Add flag handling to more instructions.

### PR DESCRIPTION
**Pull request by apmasell**
As title.

Closes https://github.com/numba/llvmlite/issues/798
Modification of https://github.com/numba/llvmlite/pull/709

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch. Is it worth checking other instructions for flag handling and getting them all done in one go? xref https://github.com/numba/llvmlite/pull/709#issuecomment-800290020

**Comment by apmasell** [comment]
I missed that comment in the original. I'll have a look.

**Comment by apmasell** [comment]
Okay. I checked which LLVM instructions support fast-math and fneg is included; everything else has been covered. The fneg function is the only one to use `_unop`...is that something that other unary instructions should be transitioning to? It seems to have flags support anyway.

Also, I realised a number of the changes used a default list parameter, so I changed them to an empty tuple to avoid mutability issues.

**Comment by stuartarchibald** [comment]
> Okay. I checked which LLVM instructions support fast-math and fneg is included; everything else has been covered.

Thanks for checking.

>The fneg function is the only one to use `_unop`...is that something that other unary instructions should be transitioning to? It seems to have flags support anyway.

I don't think there are any other unary operations in the builder API that have directly equivalent LLVM operations? Seems like the `_*op*('<operation name>')` decorator family rely on there being a named operation in LLVM.

> Also, I realised a number of the changes used a default list parameter, so I changed them to an empty tuple to avoid mutability issues.

Thanks.

**Comment by stuartarchibald** [comment]
@sklam could you take a look at this please, whilst minor, this is a modification/continuation of a patch I authored https://github.com/numba/llvmlite/pull/709. Many thanks.

**Review by sklam — APPROVED** [review]
LGTM!

@apmasell, congrats on getting your first PR for merge for llvmlite!

**Pull request merged**
