### PR TITLE
fixup LLVM versions in version compat table

### PR DESCRIPTION
**Pull request by esc**
As title

### CODE REVIEW

**Comment by esc** [comment]
Fixes: https://github.com/numba/llvmlite/issues/956

**Comment by esc** [comment]
> Thanks for the quick fix! I think this clarifies it well (including the gap for LLVM 12 and 13).

I am still a bit unsure about 0.41.0 -- let's wait for an answer on that.

**Comment by esc** [comment]
So, the state is: 0.41.0 does technically support LLVM 11 -- but this is not intended. This means, before this can be merged, we need to remove the LLVM 11 specific code-paths before we can finish this PR and get it merged.

**Comment by apmasell** [comment]
Removal is in #959

**Review by apmasell — APPROVED** [review]

**Comment by YoushaaMurhij** [comment]
I think the table should be updated. v0.41.0 does not support LLVM 14.0.1 on aarch64 (but maybe later 14.x.x releases work!)

**Comment by sklam** [comment]
@YoushaaMurhij, is there a particular issue that you are referring to that cause llvm 14.0.1 to not work?

**Comment by YoushaaMurhij** [comment]
> @YoushaaMurhij, is there a particular issue that you are referring to that cause llvm 14.0.1 to not work?

Sorry for not providing enough details. I referred to the table to install `llvmlite v0.41.0` on aarch64 by building `llvm 14.0.1` first.  but, `v0.41.0` was not found using `pip install llvmlite==0.41.0` and I downgraded to `v0.40.1`.

**Comment by sklam** [comment]
ah, i see. `v0.41` is the in-development version, files on the `main` branch reflects information for that. While we don't publish `dev` version of the package, you can get it via conda with `conda install numba/label/dev::llvmlite`.

**Comment by YoushaaMurhij** [comment]
I understand. Thanks for your response.

**Pull request merged**
