### PR TITLE
Update LLVM 7 config for SVML.

### PR DESCRIPTION
**Pull request by stuartarchibald**
SVML header file used for detecting SVML built into LLVM source
has changed name, update to accommodate.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
NOTE: Check CI build logs for `SVML detected`.

**Comment by stuartarchibald** [comment]
This PR also contains a patch to fix the issue with `enum34` missing as evident on failing builds of the master branch.

**Comment by stuartarchibald** [comment]
Finding the SVML source patching at build time is now working:
Windows: https://ci.appveyor.com/project/pitrou/llvmlite/builds/19879957#L177
Linux: https://travis-ci.org/numba/llvmlite/jobs/447800391#L3040
OSX: https://travis-ci.org/numba/llvmlite/jobs/447800390#L439

**Comment by seibert** [comment]
looks good.   merging

**Pull request merged**
