### PR TITLE
Remove linking to LTO

### PR DESCRIPTION
**Pull request by isuruf**
@conda-forge, I'm planning to drop `llvm-lto-static.patch` patch

### CODE REVIEW

**Comment by esc** [comment]
@isuruf thanks for submitting this patch helping to improve llvmlite. Would it be possible to provide some more information regarding the purpose of this patch and what you would like us to do with it? Thanks!

**Comment by isuruf** [comment]
For llvmlite to be built on windows, LLVM was patched with `llvm-lto-static.patch`. This PR drops that patch and fixes llvmlite instead.

**Comment by stuartarchibald** [comment]
@isuruf thanks for the patch, this seems like a more appropriate fix given this mechanism for resolving erroneously listed shared only libraries is known. Am wondering really if LLVM should fix it, however, this reduces the patch burden so I'm inclined to merge post testing this on the build farm. Thanks again.

**Comment by stuartarchibald** [comment]
NOTE: merging this should also require an increment to the build number of `llvmdev` and futher a rebuild of `llvmdev` itself.

**Comment by stuartarchibald** [comment]
This is will be patched into the next run of `llvmdev` work. Not for Numba 0.46/llvmlite 0.30.

**Comment by esc** [comment]
A quick note on this, for #715 I have dropped the patch, but not included the section, because I only just now stumbled over this PR again.

```
# Same issue with LTO
list(REMOVE_ITEM llvm_libs "LTO")
```

So far I have build llvmdev and llvmlite and both appear to be compilable and loadable. There are still some SVML related errors but these appear unrelated to this. 

Should we now include the above stanza in #715.

**Comment by esc** [comment]
The patch was removed with #715 -- closing this now as it no longer applies.

**Pull request closed without merging**
